export const FETCH_USER = 'FETCH_USER';
export const OPEN_OBSERVATION = 'OPEN_OBSERVATION'
export const ADD_OBSERVATION = 'ADD_OBSERVATION'
export const MODIFY_OBSERVATION = 'MODIFY_OBSERVATION'
export const DELETE_OBSERVATION = 'DELETE_OBSERVATION'
